authors/urls.py
from django.urls import path
from .views import register_view, register_create, login_create, login_view, logout_view

app_name = 'authors'


urlpatterns = [
    path('register/', register_view, name='register'),
    path('register/create/', register_create, name='register_create'),
    path('login/', login_view, name='login'),
    path('login/create/', login_create, name='login_create'),
    path('logout/', logout_view, name='logout'),

]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings




# dominio.com/urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('authors/', include('authors.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.contrib import admin
from django.urls import path
from recipes.views import home, recipe, category, search, RecipeCreateView

urlpatterns = [
        path('', home, name='recipes-home'), #Home
        path('recipes/<int:id>/', recipe, name='recipes-recipe'), #Recipes
        path('recipes/category/<int:category_id>/', category, name='recipes-category'), #Categories
        path('recipes/search/', search, name='search'), #Search
        path('recipes/new/', RecipeCreateView.as_view(), name='recipe_create'),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=65) #VARCHAR(65)

    def __str__(self):
        return self.name #método mágico para nomear o model na interface



class Recipe(models.Model):
    title = models.CharField(max_length=65) #VARCHAR(65)
    description = models.CharField(max_length=165) #VARCHAR(165)
    slug = models.SlugField(unique=True) #VARCHAR
    preparation_time = models.IntegerField() #INTEGER
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField() #INTEGER
    servings_unit = models.CharField(max_length=65) #VARCHAR(65)
    preparation_steps = models.TextField() #TEXT
    preparation_steps_is_html = models.BooleanField(default=False) #BOOLEAN
    created_at = models.DateTimeField(auto_now_add=True) #TIMESTAMP
    updated_at = models.DateTimeField(auto_now=True) #TIMESTAMP
    is_published = models.BooleanField(default=False) #BOOLEAN
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d/') #VARCHAR
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True,
        blank=True, default=None
        ) #VARCHAR(65)
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
        ) #VARCHAR

    def __str__(self):
        return self.title #método mágico para nomear o model na interface






recipes/forms.py
# forms.py
from django import forms
from .models import Recipe

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = [
            'title', 'description', 'preparation_time',
            'preparation_time_unit', 'servings', 'servings_unit',
            'preparation_steps', 'cover', 'category', 'is_published'
        ]
        labels = {
            'title': 'Recipe Name',
            'description': 'Description',
            'preparation_time': 'Preparation Time',
            'preparation_steps': 'Preparation Steps',
            'cover': 'Image',
            'category': 'Category',
            'is_published': 'Published?'
        }
        

recipes/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from recipes.utils import main
from recipes.models import Recipe
from django.http import HttpResponse, Http404
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import RecipeForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


# Create your views here.

def home(request):
    recipes = Recipe.objects.filter(is_published= True)
    return render(request, 'recipes/pages/home.html',
                  context={
                      'recipes': recipes

                  })
    # HTTP Response

def category(request, category_id):
    recipes = get_list_or_404(Recipe.objects.filter(
        category__id=category_id,
        is_published=True
        )
    )
    #recipes = Recipe.objects.filter(
    #    category__id=category_id,
    #    is_published=True
    #    ).order_by('-id')
    #if not recipes:
    #    raise Http404('Not Found')
    return render(request, 'recipes/pages/category.html',
                  context={
                     'recipes': recipes,
                     'title': f'{recipes[0].category.name} -  Category | '

                  })
    # HTTP Response


def recipe(request, id):
    recipe = get_object_or_404(Recipe,
        pk=id,
        is_published = True
        ) 
    return render(request, 'recipes/pages/recipe-view.html',context={
                    'recipe': recipe,
                    'is_detail_page': True,
                  })
    # HTTP Response


def search(request):
    search_term = request.GET.get('search', '').strip()

    if not search_term:
        raise Http404('Errei, fui mlk')
    
    recipe = Recipe.objects.filter(
    Q(
        Q(title__icontains=search_term) |
        Q(description__icontains=search_term),
    ),
    is_published = True
    ).order_by('-id')
    return render(request,  'recipes/pages/search.html', context={
        'page_title': f'Search for "{search_term}" |',
        'search_term': search_term,
        'recipes': recipe


    })


class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    form_class = RecipeForm
    template_name = 'recipes/pages/recipe-new.html'
    success_url = reverse_lazy('recipes-home')  
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)




recipes/templates/recipes/partials/forms.html
<div class="main-content container">
    <form action="{% url 'authors:login_create' %}" method="POST">
        {% csrf_token %}
        <div class="form-content form-content-grid">
        {% for field in form%}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{field}}
                {% if field.help_text %}
                    <p class="help_text">
                        {{ field.help_text }}
                    </p>
                {% endif %}
                {{ field.erros }}
            </div>        
        {%endfor%}
        </div>
        {% if form.errors %}
      <div class="form-content form-content-grid">
        <div class="form-group">
          <div class="message message-error">
            There are errors in the form, please fix them and send again.
          </div>
        </div>
      </div>
      {% endif %}
        <div class="form-content form-content-grid">
            <div class="form-group">
              <button type="submit">Send</button>
            </div>
          </div>
    </form>
</div>

recipes/templates/recipes/partials/head.html
{% load static %}


<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/fontawesome.min.css" integrity="sha512-UuQ/zJlbMVAw/UU8vVBhnI4op+/tFOpQZVT+FormmIEhRSCnJWyHiBbEVgM4Uztsht41f3FzVWgLuwzUqOObKw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/brands.min.css" integrity="sha512-DJLNx+VLY4aEiEQFjiawXaiceujj5GA7lIY8CHCIGQCBPfsEG0nGz1edb4Jvw1LR7q031zS5PpPqFuPA8ihlRA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/solid.min.css" integrity="sha512-Hp+WwK4QdKZk9/W0ViDvLunYjFrGJmNDt6sCflZNkjgvNq9mY+0tMbd6tWMiAlcf1OQyqL4gn2rYp7UsfssZPA==" crossorigin="anonymous" referrerpolicy="no-referrer" />



<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{% static '/recipes/css/style.css' %}">


recipes/templates/recipes/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url 'recipes-home' %}">
                <i class="fas fa-utensils main-logo-icon"></i> 
                <span class="main-logo-text"> Recipes</span>    
            </a>
        </h1>
        <div class="header-buttons">
            {% if user.is_authenticated %}
                <a class="btn btn-primary" href="{% url 'recipe_create' %}">Add Recipe</a>
                <a class="btn btn-secondary" href="{% url 'authors:logout' %}">Logout</a>
            {% else %}
                <a class="btn btn-primary" href="{% url 'authors:login' %}">Login</a>
                <a class="btn btn-secondary" href="{% url 'authors:register' %}">Register here</a>
                <a class="btn btn-primary" href="{% url 'authors:login' %}?next={% url 'recipe_create' %}">Add Recipe</a>
            {% endif %}
        </div>
    </div>
</header>

recipes/templates/recipes/partials/messages.html
{% if messages %}
<div class="main-content center container messages-container">
    {% for message in messages %}
    <div class="message-{{message.tags}}">
        

            {{message}}

        
    </div>
    {% endfor %}
</div>
{% endif %}


recipes/templates/recipes/partials/recipe.html
{% load static %}


<div class="recipe recipe-list-item">
    <div class="recipe-cover">
        <img src="{{ recipe.cover.url }}" alt="Temporário">   
        
    </div>
    <div class="recipe-title-container">
        <h2 class="recipe-title">
            {{ recipe.title }}
        </h2>
    </div>
    <div class="recipe-author">
        
        <span class="recipe-author-user">
            <i class="fas fa-user"></i> <!--{'recipe':{'author':'first_name'}}-->
            {% if recipe.author is not None %}
                {% if recipe.author.first_name %}
                {{ recipe.author.first_name}} {{recipe.author.last_name}}
                {% else %}
                {{ recipe.author.username }}
                {% endif %}
            {% else %}
        </span>
             Desconhecido
            {% endif %}
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
                {{ recipe.created_at }}
        </span>
        {% if recipe.category is not None%}
        <span class="recipe-author-item">
            <a href="{% url 'recipes-category' recipe.category.id %}">
                <i class="fas fa-layer-group"></i>
                <span> {{ recipe.category.name }}</span>
            </a>
        </span>
        {% endif %}
    </div>

    <div class="recipe-content">
        <p> {{ recipe.description}}</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time}} {{ recipe.preparation_time_unit}}

            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{recipe.servings}} {{recipe.servings_unit}}

            </div>
        </div>

        

    </div>
    {% if is_detail_page is not True %}
    <footer class="recipe-footer">
        <a class="recipe-read-more button button-dark button full-width" href="{% url 'recipes-recipe' recipe.id %}">
            <i class="fas fa-eye">
                <span>ver mais...</span>
            </i>
        </a>

    </footer>
    {% endif %}

    {% if is_detail_page is True %}
    <div class="preparation-steps">
        {% if recipe.preparation_steps_is_html is True %}
            {{ recipe.preparation_steps | safe }}
        {% else %}
            {{ recipe.preparation_steps }}

        {% endif %}
    </div>
    {% endif %}
</div>


recipes/templates/recipes/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="{% url 'search' %}" method="GET" class="search-form">
            <input type="search" class="search-input" name="search" 
            value="{{ search_term }}" required>
            <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>